### ISSUE TITLE
dubbo3 protocol buffer插件不存在

### ISSUE THREAD

**Issue by xiejiajun** [dubbogo/triple#2]
@LaurenceLiZhixin  github.com/apache/dubbo-go/protocol/dubbo3/protoc-gen-dubbo3 是不是忘记提交到dubbo-go代码仓库了？

**Comment by LaurenceLiZhixin** [comment]
> 
> 
> @LaurenceLiZhixin github.com/apache/dubbo-go/protocol/dubbo3/protoc-gen-dubbo3 是不是忘记提交到dubbo-go代码仓库了？

待3月底或4月初正式发版后，即可合入3.0分支。
