### ISSUE TITLE
windows未生成xx_triple.pb.go

### ISSUE THREAD

**Issue by torvalds4zh** [dubbogo/triple#49]
protoc --go_out=.  --go-triple_out=.  .\xx.proto 生成不了xx_triple.pb.go

libprotoc 3.21.9
protoc-gen-go.exe v1.28.1
protoc-gen-go-triple 1.0.5

**Comment by AlexStocks** [comment]
’--go-triple_out=‘ 和 proto 文件之间加上空格啊，譬如 
"protoc --go_out=. --go-triple_out=.\  . .\xx.proto"

**Comment by torvalds4zh** [comment]
> ’--go-triple_out=‘ 和 proto 文件之间加上空格啊，譬如 "protoc --go_out=. --go-triple_out=.\ . .\xx.proto"

有的，不会犯这种问题的，试了好几遍了。同事的电脑就可以

**Comment by torvalds4zh** [comment]
> ’--go-triple_out=‘ 和 proto 文件之间加上空格啊，譬如 "protoc --go_out=. --go-triple_out=.\ . .\xx.proto"
![路特斯飞书20221111-205051](https://user-images.githubusercontent.com/17917663/201344658-59c07f9d-89bd-4b63-9a61-4b38996e28e8.jpeg)
